### ISSUE TITLE
Phase processing without task information

### ISSUE THREAD

**Issue by tsalo** [ostanley/phaseprep#3]
@ostanley, my understanding of the current workflow is that it requires task and rest timing information- specifically from a block design.

Do you plan to support phase processing/regression in the absence of task information? I think that [Curtis, Hutchison, & Menon (2014)](https://www.sciencedirect.com/science/article/pii/S1053811914004649) used a band-pass filter before estimating the standard deviations of the signal and phase for resting-state data, but in similar cases like film-viewing or other naturalistic paradigms, I don't how comfortable I feel with just applying a one-size-fits-all filter. Is that your preferred approach?

**Comment by ostanley** [comment]
There are several ways to implement phase regression for different
paradigms and my long term goal is to have multiple implementations that
can be compared. I have this started but is isn't tested and therefore is
not pushed. I should have it pushed before Xmas.

I haven't thought about naturalistic viewing specifically I will think on
this and get back to you later this week. I understand your hesitation with
the band pass but I need to familiarize myself with naturalistic paradigm
analysis a bit more before I weigh in. Would you be able to share some
recommendations on key papers outside of Hasson?

**Comment by tsalo** [comment]
> There are several ways to implement phase regression for different paradigms and my long term goal is to have multiple implementations that can be compared.

I was also thinking about integration with workflows like fMRIPrep, where task information is not expected. I believe that phase regression needs to happen early in preprocessing, so I don't think it's something that could be postponed until after preprocessing with fMRIPrep.

If it's not possible to use just the imaging data, though, I'm sure the developers would be willing to support task info.

> Would you be able to share some recommendations on key papers outside of Hasson?

I'm definitely not an expert on naturalistic fMRI, but the first things that come to mind are functional alignment like SRM (e.g., [Turek et al., 2018](https://www.intel.ai/wp-content/uploads/sites/69/Capturing-Shared-and-Individual-Information-in-fMRI-Data.pdf)), standard annotation-based analysis like that implemented in [NeuroScout](https://neuroscout.org), or annotation-based decoding like in [Huth et al. (2016)](https://www.frontiersin.org/articles/10.3389/fnsys.2016.00081).

**Comment by tsalo** [comment]
Since this repo is no longer maintained, I'm going to close this issue.

However, I just want to include one unrelated request for @brettliem. Since your fork is now the maintained version of the workflow, would you mind enabling issues in your repo settings?
